import black from './animephotos/black.png';
import boruto from './animephotos/boruto.png';
import dandadan from './animephotos/dandadan.png';
import fullmetal from './animephotos/fullmetal.png';
import spyxfamily2 from './animephotos/spyxfamily2.png';
import chainsaw from './animephotos/chainsaw.png';
import tbate from './animephotos/tbate.png';
import myhero from './animephotos/myhero.png';
import thebrilliant from './animephotos/thebrilliant.png';
import guiltygear from './animephotos/guiltygear.png';
import buchigiri from './animephotos/buchigiri.png';
import drstone from './animephotos/drstone.png';
import akudamadrive from './animephotos/akudamadrive.png';
import solo from './animephotos/solo.png';
import byebyeearth from './animephotos/byebyeearth.png';
import bluelock from './animephotos/bluelock.png';
import kaiju from './animephotos/kaiju.png';
import demonslayer from './animephotos/demonslayer.png';
import fireforse from './animephotos/fireforse.png';
import jujutsu from './animephotos/jujutsu.png';
import windbreaker from './animephotos/windbreaker.png';
import darling from './animephotos/darling.png';
import sao from './animephotos/sao.png';
import vinland from './animephotos/vinland.png';
import toyoureternity from './animephotos/toyoureternity.png';
import amiactually from './animephotos/amiactually.png';
import samurai from './animephotos/samurai.png';
import trigun from './animephotos/trigun.png';
import godofhigh from './animephotos/godofhigh.png';
import lycorisrecoil from './animephotos/lycorisrecoil.png';
import goblinslayer from './animephotos/goblinslayer.png';
import elfbride from './animephotos/elfbride.png';
import returnermagic from './animephotos/returnermagic.png';
import souleater from './animephotos/souleater.png';
import classroomofelite from './animephotos/classroomofelite.png';
import frieren from './animephotos/frieren.png';
import towerofgod from './animephotos/towerofgod.png';
import shangri from './animephotos/shangri.png';
import fairytail from './animephotos/fairytail.png';
import gintama from './animephotos/gintama.png';
import blackbutler from './animephotos/blackbutler.png';
import naruto from './animephotos/naruto.png';
import codegeass from './animephotos/codegeass.png';
import mushoku from './animephotos/mushoku.png';
import slime from './animephotos/slime.png';
import konosuba from './animephotos/konosuba.png';
import rezero from './animephotos/rezero.png';
import rascal from './animephotos/rascal.png';
import shikimori from './animephotos/shikimori.png';
import angelnextdoor from './animephotos/angelnextdoor.png';
import morethanmarried from './animephotos/morethanmarried.png';
import rentagirl from './animephotos/rentagirl.png';
import vanitas from './animephotos/vanitas.png';
import dailylifeking from './animephotos/dailylifeking.png';






const animeData = [

  {
    id: "black-clover",
    title: "Black Clover",
    subtitle: "Sub | Dub",
    image: [black],
    rating: "4.7★ (210k)",
    season: "1 Season",
    episode: "170 Episodes",
    desc: "Asta, born without magic, aims to become the Wizard King with his anti-magic grimoire. Alongside Yuno, he faces trials in the Clover Kingdom.",
  },
  {
    id: "fullmetal-alchemist-brotherhood",
    title: "Fullmetal Alchemist: Brotherhood",
    subtitle: "Sub | Dub",
    image: [fullmetal],
    rating: "4.9★ (80k)",
    season: "1 Season",
    episode: "64 Episodes",
    desc: "Edward and Alphonse Elric seek the Philosopher’s Stone to restore their bodies, uncovering a dark alchemical conspiracy.",
  },
  {
    id: "spy-x-family",
    title: "SPY x FAMILY",
    subtitle: "Sub | Dub",
    image: [spyxfamily2],
    rating: "4.8★ (350k)",
    season: "3 Seasons",
    episode: "50 Episodes",
    desc: "Spy Twilight, assassin Yor, and telepath Anya pose as a family to maintain peace, balancing espionage with domestic comedy.",
  },
  {
    id: "dan-da-dan",
    title: "DAN DA DAN",
    subtitle: "Sub | Dub",
    image: [dandadan],
    rating: "4.9★ (190k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Momo and Ken unleash supernatural chaos, battling ghosts and aliens in a thrilling mix of action, humor, and romance.",
  },
  {
    id: "boruto-naruto-next-generations",
    title: "Boruto: Naruto Next Generations",
    subtitle: "Sub | Dub",
    image: [boruto],
    rating: "4.0★ (85k)",
    season: "1 Season",
    episode: "293 Episodes",
    desc: "Boruto, Naruto’s son, navigates a peaceful ninja world, facing new threats and uncovering family secrets with Team 7.",
  },
  {
    id: "chainsaw-man",
    title: "Chainsaw Man",
    subtitle: "Sub | Dub",
    image: [chainsaw],
    rating: "4.8★ (210k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Denji, as Chainsaw Man, hunts devils for Public Safety, balancing brutal battles with dreams of a normal life.",
  },
  {
    id: "the-beginning-after-the-end",
    title: "The Beginning After the End",
    subtitle: "Sub | Dub",
    image: [tbate],
    rating: "4.7★ (80k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Reincarnated as Arthur Leywin, King Grey masters magic in a new world, seeking redemption through adventure.",
  },
  {
    id: "guilty-gear-strive-dual-rulers",
    title: "Guilty Gear Strive: Dual Rulers",
    subtitle: "Sub | Dub",
    image: [guiltygear],
    rating: "4.6★ (90k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Sol Badguy and fighters compete in a post-apocalyptic tournament, blending action and redemption in a Guilty Gear-inspired world.",
  },
  {
    id: "my-hero-academia",
    title: "My Hero Academia",
    subtitle: "Sub | Dub",
    image: [myhero],
    rating: "4.8★ (200k)",
    season: "8 Seasons",
    episode: "172 Episodes",
    desc: "Izuku Midoriya inherits All Might’s powers, training at UA High to become a hero in the climactic Final War arc.",
  },
  {
    id: "the-brilliant-healers-new-life-in-the-shadows",
    title: "The Brilliant Healer's New Life in the Shadows",
    subtitle: "Sub | Dub",
    image: [thebrilliant],
    rating: "4.2★ (70k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "A once-ignored healer uses his mastery discreetly, aiding others in a fantasy world while uncovering hidden dangers.",
  },
  {
    id: "akudama-drive",
    title: "Akudama Drive",
    subtitle: "Sub | Dub",
    image: [akudamadrive],
    rating: "4.3★ (75k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Criminals, the Akudama, undertake a chaotic heist in dystopian Japan, joined by an ordinary girl against a corrupt system.",
  },
  {
    id: "dan-da-dan",
    title: "DAN DA DAN",
    subtitle: "Sub | Dub",
    image: [dandadan],
    rating: "4.9★ (190k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Momo and Ken face ghosts and aliens after awakening supernatural forces, mixing action, comedy, and romance.",
  },
  {
    id: "dr-stone",
    title: "Dr. Stone",
    subtitle: "Sub | Dub",
    image: [drstone],
    rating: "4.7★ (90k)",
    season: "4 Seasons",
    episode: "69 Episodes",
    desc: "Senku rebuilds civilization with science post-petrification, facing challenges to create a new scientific world.",
  },
  {
    id: "buchigiri",
    title: "Buchigiri?!",
    subtitle: "Sub | Dub",
    image: [buchigiri],
    rating: "4.1★ (65k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Delinquent Arajin navigates gang wars at a school for misfits, with supernatural fights shaping his journey.",
  },
  {
    id: "chainsaw-man",
    title: "Chainsaw Man",
    subtitle: "Sub | Dub",
    image: [chainsaw],
    rating: "4.8★ (210k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Denji hunts devils as Chainsaw Man, facing monstrous foes while pursuing a simple life with Public Safety.",
  },
  {
    id: "kaiju-no-8",
    title: "Kaiju No. 8",
    subtitle: "Sub | Dub",
    image: [kaiju],
    rating: "4.7★ (85k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Kafka, a kaiju-human hybrid, joins the Defense Force to fight monsters, hiding his secret to protect humanity.",
  },
  {
    id: "blue-lock",
    title: "Blue Lock",
    subtitle: "Sub | Dub",
    image: [bluelock],
    rating: "4.8★ (95k)",
    season: "2 Seasons",
    episode: "37 Episodes",
    desc: "Yoichi Isagi competes in Blue Lock to become Japan’s ultimate striker, facing intense soccer matches to prove his ego.",
  },
  {
    id: "solo-leveling",
    title: "Solo Leveling",
    subtitle: "Sub | Dub",
    image: [solo],
    rating: "4.8★ (220k)",
    season: "2 Seasons",
    episode: "25 Episodes",
    desc: "Sung Jinwoo rises from weak hunter to Shadow Monarch, battling S-Rank demons with his infinite leveling system.",
  },
  {
    id: "bye-bye-earth",
    title: "Bye Bye, Earth",
    subtitle: "Sub | Dub",
    image: [byebyeearth],
    rating: "4.2★ (60k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: " Belle, a human in an animal-ruled world, seeks belonging with her cursed sword in a beastly society.",
  },
  {
    id: "dan-da-dan",
    title: "DAN DA DAN",
    subtitle: "Sub | Dub",
    image: [dandadan],
    rating: "4.9★ (190k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Momo and Ken’s bet unleashes paranormal chaos, facing ghosts and aliens in a wild action-comedy adventure.",
  },
  {
    id: "demon-slayer-kimetsu-no-yaiba",
    title: "Demon Slayer: Kimetsu no Yaiba",
    subtitle: "Sub | Dub",
    image: [demonslayer],
    rating: "4.8★ (250k)",
    season: "5 Seasons",
    episode: "63 Episodes",
    desc: "Tanjiro fights to save his demonized sister Nezuko, battling Muzan and his forces as a Demon Slayer.",
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    subtitle: "Sub | Dub",
    image: [jujutsu],
    rating: "4.8★ (230k)",
    season: "2 Seasons",
    episode: "47 Episodes",
    desc: "Yuji Itadori, host to a powerful curse, trains at Jujutsu High, exorcising curses while facing dark threats.",
  },
  {
    id: "fire-force",
    title: "Fire Force",
    subtitle: "Sub | Dub",
    image: [fireforse],
    rating: "4.6★ (80k)",
    season: "3 Seasons",
    episode: "60 Episodes",
    desc: "Shinra and Company 8 battle spontaneous combustion, uncovering a conspiracy tied to the Evangelist in Tokyo.",
  },
  {
    id: "wind-breaker",
    title: "Wind Breaker",
    subtitle: "Sub | Dub",
    image: [windbreaker],
    rating: "4.7★ (75k)",
    season: "2 Seasons",
    episode: "26 Episodes",
    desc: "Haruka Sakura joins Furin High’s fighters, protecting their town through brawls and forging strong bonds.",
  },
  {
    id: "solo-leveling",
    title: "Solo Leveling",
    subtitle: "Sub | Dub",
    image: [solo],
    rating: "4.8★ (220k)",
    season: "2 Seasons",
    episode: "25 Episodes",
    desc: "Sung Jinwoo’s leveling system makes him the Shadow Monarch, facing epic dungeon battles with S-Rank demons.",
  },
  {
    id: "sword-art-online",
    title: "Sword Art Online",
    subtitle: "Sub | Dub",
    image: [sao],
    rating: "4.5★ (100k)",
    season: "4 Seasons",
    episode: "96 Episodes",
    desc: "Kirito fights to escape a deadly VR game, conquering Aincrad’s floors and uncovering digital conspiracies.",
  },
  {
    id: "vinland-saga",
    title: "Vinland Saga",
    subtitle: "Sub | Dub",
    image: [vinland],
    rating: "4.8★ (90k)",
    season: "2 Seasons",
    episode: "48 Episodes",
    desc: "Thorfinn’s Viking journey seeks revenge, leading to a quest for peace and the fabled Vinland through war and slavery.",
  },
  {
    id: "to-your-eternity",
    title: "To Your Eternity",
    subtitle: "Sub | Dub",
    image: [toyoureternity],
    rating: "4.6★ (70k)",
    season: "2 Seasons",
    episode: "40 Episodes",
    desc: "Immortal Fushi learns humanity through shifting forms, facing love, loss, and a mysterious foe across eras.",
  },
  {
    id: "darling-in-the-franxx",
    title: "Darling in the FranXX",
    subtitle: "Sub | Dub",
    image: [darling],
    rating: "4.3★ (80k)",
    season: "1 Season",
    episode: "24 Episodes",
    desc: "Teens pilot FranXX mechs in a dystopian world, with Hiro and Zero Two’s bond challenging their controlled society.",
  },
  {
    id: "fullmetal-alchemist-brotherhood",
    title: "Fullmetal Alchemist: Brotherhood",
    subtitle: "Sub | Dub",
    image: [fullmetal],
    rating: "4.9★ (80k)",
    season: "1 Season",
    episode: "64 Episodes",
    desc: "Edward and Alphonse hunt the Philosopher’s Stone to restore their bodies, revealing dark alchemical secrets.",
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    subtitle: "Sub | Dub",
    image: [jujutsu],
    rating: "4.8★ (230k)",
    season: "2 Seasons",
    episode: "47 Episodes",
    desc: "Yuji, cursed by a powerful spirit, trains as a jujutsu sorcerer, battling evil curses and inner demons.",
  },
  {
    id: "demon-slayer-kimetsu-no-yaiba",
    title: "Demon Slayer: Kimetsu no Yaiba",
    subtitle: "Sub | Dub",
    image: [demonslayer],
    rating: "4.8★ (250k)",
    season: "5 Seasons",
    episode: "63 Episodes",
    desc: "Tanjiro’s quest to save Nezuko pits him against Muzan, with the Demon Slayer Corps facing intense battles.",
  },
  {
    id: "solo-leveling",
    title: "Solo Leveling",
    subtitle: "Sub | Dub",
    image: [solo],
    rating: "4.8★ (220k)",
    season: "2 Seasons",
    episode: "25 Episodes",
    desc: "Sung Jinwoo rises to Shadow Monarch, battling S-Rank demons with his unique leveling system in dungeons.",
  },
  {
    id: "sword-art-online",
    title: "Sword Art Online",
    subtitle: "Sub | Dub",
    image: [sao],
    rating: "4.5★ (100k)",
    season: "4 Seasons",
    episode: "96 Episodes",
    desc: "Kirito navigates a virtual death game, forging alliances and uncovering dark plots in Aincrad’s floors.",
  },
  {
    id: "kaiju-no-8",
    title: "Kaiju No. 8",
    subtitle: "Sub | Dub",
    image: [kaiju],
    rating: "4.7★ (85k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Kafka, a kaiju-human hybrid, fights monsters in the Defense Force, hiding his identity to protect humanity.",
  },
  {
    id: "the-god-of-high-school",
    title: "The God of High School",
    subtitle: "Sub | Dub",
    image: [godofhigh],
    rating: "4.4★ (70k)",
    season: "1 Season",
    episode: "13 Episodes",
    desc: "Jin Mori battles in a supernatural martial arts tournament, uncovering his hidden powers and a secret organization.",
  },
  {
    id: "lycoris-recoil",
    title: "Lycoris Recoil",
    subtitle: "Sub | Dub",
    image: [lycorisrecoil],
    rating: "4.6★ (75k)",
    season: "1 Season",
    episode: "13 Episodes",
    desc: "Lycoris agents Chisato and Takina maintain peace through covert missions, with clashing ideals fueling their growth.",
  },
  {
    id: "samurai-champloo",
    title: "Samurai Champloo",
    subtitle: "Sub | Dub",
    image: [samurai],
    rating: "4.7★ (85k)",
    season: "1 Season",
    episode: "26 Episodes",
    desc: "Fuu hires samurai Mugen and Jin to find a mysterious man, blending swordplay and hip-hop in Edo-era Japan.",
  },
  {
    id: "am-i-actually-the-strongest",
    title: "Am I Actually the Strongest?",
    subtitle: "Sub | Dub",
    image: [amiactually],
    rating: "4.2★ (65k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Reincarnated Haruto hides his overpowered abilities, but conflicts in a fantasy world force him to reveal his strength.",
  },
  {
    id: "trigun",
    title: "Trigun",
    subtitle: "Sub | Dub",
    image: [trigun],
    rating: "4.6★ (80k)",
    season: "1 Season",
    episode: "26 Episodes",
    desc: "Vash, a pacifist gunslinger with a bounty, roams a desert planet, revealing his past and humanity’s fate.",
  },
  {
    id: "classroom-of-the-elite",
    title: "Classroom of the Elite",
    subtitle: "Sub | Dub",
    image: [classroomofelite],
    rating: "4.7★ (90k)",
    season: "3 Seasons",
    episode: "37 Episodes",
    desc: "Kiyotaka Ayanokoji manipulates events at an elite school, navigating a merit-based hierarchy with cunning.",
  },
  {
    id: "an-archdemons-dilemma-how-to-love-your-elf-bride",
    title: "An Archdemon’s Dilemma: How to Love Your Elf Bride",
    subtitle: "Sub | Dub",
    image: [elfbride],
    rating: "4.3★ (70k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Archdemon Zagan frees elf Nephy, sparking an awkward romance in a magical world filled with danger.",
  },
  {
    id: "a-returners-magic-should-be-special",
    title: "A Returner’s Magic Should Be Special",
    subtitle: "Sub | Dub",
    image: [returnermagic],
    rating: "4.3★ (65k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Desir Arman, sent back in time, trains at a magic academy to prevent a world-ending disaster.",
  },
  {
    id: "soul-eater",
    title: "Soul Eater",
    subtitle: "Sub | Dub",
    image: [souleater],
    rating: "4.6★ (80k)",
    season: "1 Season",
    episode: "51 Episodes",
    desc: "Maka and Soul hunt evil souls at Death Weapon Meister Academy, aiming to create a Death Scythe.",
  },
  {
    id: "goblin-slayer",
    title: "Goblin Slayer",
    subtitle: "Sub | Dub",
    image: [goblinslayer],
    rating: "4.4★ (75k)",
    season: "2 Seasons",
    episode: "24 Episodes",
    desc: "Goblin Slayer hunts goblins after a tragedy, facing brutal battles and a greater evil with allies.",
  },
  {
    id: "frieren-beyond-journeys-end",
    title: "Frieren: Beyond Journey’s End",
    subtitle: "Sub | Dub",
    image: [frieren],
    rating: "4.9★ (200k)",
    season: "1 Season",
    episode: "28 Episodes",
    desc: "Elf mage Frieren reflects on her immortal life, honoring past comrades’ wishes in a poignant journey.",
  },
  {
    id: "shangri-la-frontier",
    title: "Shangri-La Frontier",
    subtitle: "Sub | Dub",
    image: [shangri],
    rating: "4.6★ (80k)",
    season: "2 Seasons",
    episode: "38 Episodes",
    desc: "Gamer Rakuro tackles VR game Shangri-La Frontier, uncovering hidden secrets in epic challenges.",
  },
  {
    id: "tower-of-god",
    title: "Tower of God",
    subtitle: "Sub | Dub",
    image: [towerofgod],
    rating: "4.5★ (70k)",
    season: "2 Seasons",
    episode: "26 Episodes",
    desc: "Bam climbs a mysterious Tower to find Rachel, facing tests that reveal secrets about himself.",
  },
  {
    id: "demon-slayer-kimetsu-no-yaiba",
    title: "Demon Slayer: Kimetsu no Yaiba",
    subtitle: "Sub | Dub",
    image: [demonslayer],
    rating: "4.8★ (250k)",
    season: "5 Seasons",
    episode: "63 Episodes",
    desc: "Tanjiro battles Muzan to save his demonized sister Nezuko, with the Demon Slayer Corps at stake.",
  },
  {
    id: "sword-art-online",
    title: "Sword Art Online",
    subtitle: "Sub | Dub",
    image: [sao],
    rating: "4.5★ (100k)",
    season: "4 Seasons",
    episode: "96 Episodes",
    desc: "Kirito fights to escape a virtual death game, forging alliances and uncovering dark plots.",
  },
  {
    id: "code-geass",
    title: "Code Geass",
    subtitle: "Sub | Dub",
    image: [codegeass],
    rating: "4.8★ (95k)",
    season: "2 Seasons",
    episode: "50 Episodes",
    desc: "Lelouch, with the power of Geass, leads a rebellion against an empire, using strategic genius.",
  },
  {
    id: "gintama",
    title: "Gintama",
    subtitle: "Sub | Dub",
    image: [gintama],
    rating: "4.8★ (85k)",
    season: "8 Seasons",
    episode: "367 Episodes",
    desc: "Gintoki, a samurai in alien-occupied Japan, takes odd jobs with his team, blending comedy and epic battles.",
  },
  {
    id: "fairy-tail",
    title: "Fairy Tail",
    subtitle: "Sub | Dub",
    image: [fairytail],
    rating: "4.6★ (90k)",
    season: "3 Seasons",
    episode: "328 Episodes",
    desc: "Natsu and the Fairy Tail guild embark on magical adventures, battling dark forces and forging unbreakable bonds.",
  },
  {
    id: "naruto",
    title: "Naruto",
    subtitle: "Sub | Dub",
    image: [naruto],
    rating: "4.7★ (200k)",
    season: "5 Seasons",
    episode: "220 Episodes",
    desc: "Naruto Uzumaki, a young ninja, dreams of becoming Hokage, overcoming prejudice and battles to protect his village.",
  },
  {
    id: "black-butler",
    title: "Black Butler",
    subtitle: "Sub | Dub",
    image: [blackbutler],
    rating: "4.5★ (80k)",
    season: "4 Seasons",
    episode: "46 Episodes",
    desc: "Ciel Phantomhive and his demon butler Sebastian solve mysteries in Victorian England, bound by a dark contract.",
  },
  {
    id: "rezero-starting-life-in-another-world",
    title: "Re:ZERO - Starting Life in Another World",
    subtitle: "Sub | Dub",
    image: [rezero],
    rating: "4.7★ (100k)",
    season: "3 Seasons",
    episode: "50 Episodes",
    desc: "Subaru, trapped in a fantasy world, uses his time-loop ability to save Emilia from deadly fates.",
  },
  {
    id: "mushoku-tensei-jobless-reincarnation",
    title: "Mushoku Tensei: Jobless Reincarnation",
    subtitle: "Sub | Dub",
    image: [mushoku],
    rating: "4.8★ (95k)",
    season: "2 Seasons",
    episode: "48 Episodes",
    desc: "A reincarnated man, as Rudeus, masters magic in a new world, seeking redemption through adventure and growth.",
  },
  {
    id: "sword-art-online",
    title: "Sword Art Online",
    subtitle: "Sub | Dub",
    image: [sao],
    rating: "4.5★ (100k)",
    season: "4 Seasons",
    episode: "96 Episodes",
    desc: "Kirito battles through virtual worlds to escape, facing deadly challenges and digital conspiracies.",
  },
  {
    id: "konosuba-gods-blessing-on-this-wonderful-world",
    title: "KonoSuba: God’s Blessing on This Wonderful World!",
    subtitle: "Sub | Dub",
    image: [konosuba],
    rating: "4.7★ (85k)",
    season: "3 Seasons",
    episode: "36 Episodes",
    desc: "Kazuma, reincarnated in a fantasy world, teams with quirky adventurers for comedic and chaotic quests.",
  },
  {
    id: "that-time-i-got-reincarnated-as-a-slime",
    title: "That Time I Got Reincarnated as a Slime",
    subtitle: "Sub | Dub",
    image: [slime],
    rating: "4.7★ (90k)",
    season: "3 Seasons",
    episode: "62 Episodes",
    desc: "Satoru, reborn as slime Rimuru, builds a monster nation in a fantasy world, forging peace through power.",
  },
  {
    id: "rascal-does-not-dream-of-bunny-girl-senpai",
    title: "Rascal Does Not Dream of Bunny Girl Senpai",
    subtitle: "Sub | Dub",
    image: [rascal],
    rating: "4.6★ (80k)",
    season: "1 Season",
    episode: "13 Episodes",
    desc: "Sakuta helps girls with supernatural adolescence syndrome, starting with Mai, in a heartfelt and mysterious tale.",
  },
  {
    id: "more-than-a-married-couple-but-not-lovers",
    title: "More Than a Married Couple, But Not Lovers",
    subtitle: "Sub | Dub",
    image: [morethanmarried],
    rating: "4.4★ (70k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Jiro and Akari, paired as a fake couple for a school project, navigate romantic tension and personal feelings.",
  },
  {
    id: "rent-a-girlfriend",
    title: "Rent-a-Girlfriend",
    subtitle: "Sub | Dub",
    image: [rentagirl],
    rating: "4.3★ (65k)",
    season: "3 Seasons",
    episode: "36 Episodes",
    desc: "Kazuya rents girlfriend Chizuru, sparking a messy romance filled with fake dates and real emotions.",
  },
  {
    id: "shikimoris-not-just-a-cutie",
    title: "Shikimori’s Not Just a Cutie",
    subtitle: "Sub | Dub",
    image: [shikimori],
    rating: "4.4★ (70k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Shikimori, a cool and caring girlfriend, protects clumsy Izumi in a sweet, comedic high school romance.",
  },
  {
    id: "the-angel-next-door-spoils-me-rotten",
    title: "The Angel Next Door Spoils Me Rotten",
    subtitle: "Sub | Dub",
    image: [angelnextdoor],
    rating: "4.5★ (75k)",
    season: "1 Season",
    episode: "12 Episodes",
    desc: "Amane’s kind neighbor Mahiru, an angelic school idol, forms a heartwarming bond through shared moments.",
  },
  {
    id: "the-daily-life-of-the-immortal-king",
    title: "The Daily Life of the Immortal King",
    subtitle: "Sub | Dub",
    image: [dailylifeking],
    rating: "4.3★ (60k)",
    season: "4 Seasons",
    episode: "52 Episodes",
    desc: "Wang Ling, an overpowered immortal teen, hides his strength to live a normal high school life.",
  },
  {
    id: "the-case-study-of-vanitas",
    title: "The Case Study of Vanitas",
    subtitle: "Sub | Dub",
    image: [vanitas],
    rating: "4.5★ (70k)",
    season: "2 Seasons",
    episode: "24 Episodes",
    desc: "Vanitas, wielding a cursed book, heals vampires in 19th-century Paris, joined by Noé in a gothic adventure.",
  },
  {
    id: "vinland-saga",
    title: "Vinland Saga",
    subtitle: "Sub | Dub",
    image: [vinland],
    rating: "4.8★ (90k)",
    season: "2 Seasons",
    episode: "48 Episodes",
    desc: "Thorfinn seeks revenge, but his Viking journey through war and slavery leads to a quest for Vinland.",
  },
  {
    id: "tower-of-god",
    title: "Tower of God",
    subtitle: "Sub | Dub",
    image: [towerofgod],
    rating: "4.5★ (70k)",
    season: "2 Seasons",
    episode: "26 Episodes",
    desc: "Bam climbs a mysterious Tower to find Rachel, facing deadly tests that reveal his true nature.",
  },
  {
    id: "dr-stone",
    title: "Dr. Stone",
    subtitle: "Sub | Dub",
    image: [drstone],
    rating: "4.7★ (90k)",
    season: "4 Seasons",
    episode: "69 Episodes",
    desc: "Senku uses science to rebuild civilization after humanity’s petrification, facing challenges for a new world.",
  },
  {
    id: "blue-lock",
    title: "Blue Lock",
    subtitle: "Sub | Dub",
    image: [bluelock],
    rating: "4.8★ (95k)",
    season: "2 Seasons",
    episode: "37 Episodes",
    desc: "Yoichi Isagi battles in Blue Lock to become Japan’s ultimate striker, proving his ego in intense soccer matches.",
  }

];

export default animeData;